### ISSUE TITLE
Question: Data parallel vs Split model training

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/nmt#11]
The currently implemented setup allows to split the model across multiple GPUs by distributing the layers.
Is this approach prefered over having the same model on multiple GPUs and doing data parallel training by increasing the batch size?

What are pros and cons of the two approaches?

**Comment by ebrevdo** [comment]
If doing data parallel training, you place multiple layers on a single GPU.  This works well if you have enough RAM to perform the computations of multiple layers all on a single GPU.  Otherwise you'll run out of memory quickly.  Just FYI; this kind of question is better suited for stack overflow or tensorflow discuss mailing list.
