### ISSUE TITLE
Adam creates different model checkpoint sizes for best_bleu and out_dir

### ISSUE THREAD

**Issue by vineetm** [tensorflow/nmt#130]
Hi,

I noticed that when my model is trained using 'Adam' different checkpoint sizes are created for `out_dir` and `out_dir/best_bleu`. out_dir checkpoints are larger in size that `best_bleu`

Further if I say wish to continue training from best_bleu model checkpoint say by copying the state from `out_dir/best_bleu` to `out_dir', I get this error
```
NotFoundError (see above for traceback): Key embeddings/decoder/embedding_decoder/Adam_1 not found in checkpoint
```

Is this expected? Is best_bleu directory not meant to restart training, and only for inference? I do not face any issue while doing inference with best_bleu directory... Is there a workaround, so best_bleu also saves the complete model...?

**Comment by oahziur** [comment]
@vineetm 

We save the inference model's parameters during the external eval (decoding and computing the bleu score). For sgd, the set of parameters should be the same, but it won't have adam's parameters since it is not a training model.

As a workaround for Adam, you can pass the train_model into _external_eval, and use the train_model's saver here: https://github.com/tensorflow/nmt/blob/master/nmt/train.py#L455

**Comment by vineetm** [comment]
Thanks for your quick response @oahziur I will try the approach you suggested.
